version: '3'
services:
  frontend:
    image: frontend
    volumes:
      - ./front-end/default.conf:/etc/nginx/conf.d/default.conf
    build:
      context: front-end
      dockerfile: Dockerfile
      args:
        TESTURL: "http://localhost:8000"
        ENVIRONMENT: e2e
    ports:
      - "8080:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile-e2e
    user: node
    ports:
      - "8000:9428"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9428/api/status || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
  tests:
    image: frontendtest
    build:
      context: front-end
      dockerfile: Dockerfile-e2e
    user: pwuser
    depends_on:
      - backend
      - frontend
    volumes:
      - test-results:/usr/local/app/test-results
      - playwright-report:/usr/local/app/playwright-report
    network_mode: "host"
volumes:
  test-results:
  playwright-report:
