services:
  backend:
    container_name: backend
    image: backend
    build: ../backend
    ports:
      - "8000:9428"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9428 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  frontend:
    container_name: frontend
    image: frontend
    volumes:
      - ./../front-end/default.conf:/etc/nginx/conf.d/default.conf
    build:
      context: ../front-end
      args:
        TESTURL: "http://backend:9428"
        API_URL: "http://backend:9428"
        ENVIRONMENT: production
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
